# Generated by Django 4.2.10 on 2024-03-02 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Annee_Univ', models.IntegerField()),
                ('Semestre', models.CharField(choices=[('S1', 's1'), ('S2', 's2'), ('S3', 's3'), ('S4', 's4'), ('S5', 's5'), ('S6', 's6')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=180)),
                ('Statut', models.CharField(choices=[('td', 'TD'), ('tp', 'TP')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Heure', models.CharField(choices=[('8H30-10H', '8H30-10H'), ('10H-11H30', '10H-11H30'), ('11H30-13H', '11H30-13H'), ('14H-15H30', '14h-15H30'), ('15H30-17H', '15H30-17H')], max_length=50)),
                ('Salle', models.CharField(max_length=180)),
                ('ID_Enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ID_Groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.groupe')),
                ('ID_Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Reconnaissance_Faciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encoding_visage', models.TextField()),
                ('ID_Etudient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.etudient')),
            ],
        ),
        migrations.AddField(
            model_name='etudient',
            name='Id_Groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.groupe'),
        ),
        migrations.CreateModel(
            name='Etat_Etudient_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nbr_Absence', models.IntegerField()),
                ('Nbr_Absence_Justifier', models.IntegerField()),
                ('ID_Etudient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.etudient')),
                ('ID_Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.modules')),
                ('ID_Seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.seances')),
            ],
        ),
        migrations.CreateModel(
            name='Assister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Etudient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.etudient')),
                ('ID_Seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.seances')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Justifier', models.BooleanField(default=False)),
                ('ID_Etudient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.etudient')),
                ('ID_Seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence.seances')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Modules_En',
            field=models.ManyToManyField(related_name='Enseignant', to='presence.modules'),
        ),
    ]
