# Generated by Django 4.2.10 on 2024-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_alter_enseignant_options_alter_enseignant_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etat_etudient_module',
            name='ID_Seances',
        ),
        migrations.AlterField(
            model_name='etat_etudient_module',
            name='Nbr_Absence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etat_etudient_module',
            name='Nbr_Absence_Justifier',
            field=models.IntegerField(default=0),
        ),
    ]
