# Generated by Django 4.2.10 on 2024-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_remove_etat_etudient_module_id_seances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudient',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='etudient',
            name='Incoding_Face',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudient',
            name='Is_Incoded',
            field=models.BooleanField(default=False),
        ),
    ]
