# Generated by Django 4.2.10 on 2024-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_etudient_image_etudient_incoding_face_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captured_images/')),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
