# Generated by Django 4.2.10 on 2024-04-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_etat_etudient_module_id_seances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etat_etudient_module',
            name='ID_Seances',
        ),
    ]
