# Generated by Django 4.2.10 on 2024-05-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0007_remove_etat_etudient_module_id_seances'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='MotDePasseApp',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='etat_etudient_module',
            unique_together={('ID_Etudient', 'ID_Module')},
        ),
    ]
